x-op-restart-policy: &restart_policy
  restart: unless-stopped
x-op-image: &image
  image: openproject/openproject:${TAG:-17-slim}
x-op-app: &app
  <<: [*image, *restart_policy]
  pull_policy: missing
  environment:
    OPENPROJECT_HTTPS: "${OPENPROJECT_HTTPS:-true}"
    OPENPROJECT_HOST__NAME: "${OPENPROJECT_HOST__NAME:-localhost}"
    OPENPROJECT_ADDITIONAL__HOST__NAMES: "${OPENPROJECT_ADDITIONAL__HOST__NAMES:-web}" # to allow access from hocuspocus directly
    OPENPROJECT_HSTS: "${OPENPROJECT_HSTS:-true}"
    OPENPROJECT_RAILS__CACHE__STORE: "memcache"
    OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
    OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
    OPENPROJECT_COLLABORATIVE__EDITING__HOCUSPOCUS__URL: "wss://${OPENPROJECT_HOST__NAME:-localhost}/hocuspocus"
    OPENPROJECT_COLLABORATIVE__EDITING__HOCUSPOCUS__SECRET: "${COLLABORATIVE_SERVER_SECRET:-OVERRIDE_ME_PLEASE}"
    DATABASE_URL: "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-p4ssw0rd}@db/${POSTGRES_DB:-openproject}?pool=20&encoding=unicode&reconnect=true"
    RAILS_MIN_THREADS: ${RAILS_MIN_THREADS:-4}
    RAILS_MAX_THREADS: ${RAILS_MAX_THREADS:-16}
    # set to true to enable the email receiving feature. See ./docker/cron for more options
    IMAP_ENABLED: "${IMAP_ENABLED:-false}"
    SECRET_KEY_BASE: "${SECRET_KEY_BASE:-OVERWRITE_ME}"
  volumes:
    - "${OPDATA:-./data/assets}:/var/openproject/assets"

services:
  db:
    image: postgres:${POSTGRES_VERSION:-17}
    <<: *restart_policy
    pull_policy: missing
    stop_grace_period: "3s"
    volumes:
      - "${PGDATA:-./data/postgres}:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-p4ssw0rd}
      POSTGRES_DB: ${POSTGRES_DB:-openproject}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-openproject}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    ports:
      "127.0.0.1:5437:5432"

  cache:
    image: memcached
    <<: *restart_policy
    pull_policy: missing

  web:
    <<: *app
    command: "./docker/prod/web"
    hostname: "${OPENPROJECT_HOST__NAME:-localhost}"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
      seeder:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT:-8080}${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}/health_checks/default"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  worker:
    <<: *app
    command: "./docker/prod/worker"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
      seeder:
        condition: service_completed_successfully

  cron:
    <<: *app
    command: "./docker/prod/cron"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
      seeder:
        condition: service_completed_successfully

  seeder:
    <<: *app
    command: "./docker/prod/seeder"
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started

  hocuspocus:
    image: openproject/hocuspocus:17.6.0
    pull_policy: missing
    environment:
      SECRET: ${COLLABORATIVE_SERVER_SECRET:-OVERRIDE_ME_PLEASE}
      OPENPROJECT_URL: "http://web:${APP_PORT:-8080}"
      OPENPROJECT_HTTPS: "${OPENPROJECT_HTTPS:-true}"
    <<: *restart_policy
